# Logging Configuration
version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] %(message)s'

handlers:
  console:
    class: StreamHandler
    level: INFO
    formatter: simple
    stream: ext/sys

  file:
    class: FileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/pipeline.log
    mode: 'a'

loggers:
  doc2text:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console, file]
